version: "3"

services:
  app: &app
    env_file: .env
    working_dir: /usr/app
    build:
      dockerfile: Dockerfile
      context: .
    healthcheck:
      test: "curl -f http://localhost:${PORT}/version || false"
      interval: 1s
      timeout: 3s
    ports:
      - "${PORT}:${PORT}"
