name: Build
on:
  push:
    branches:
      - main
      - master

jobs:
  eslint:
    name: "ESLint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: yarn
      - name: Check lint
        run: yarn lint

  check-types:
    runs-on: ubuntu-latest
    name: "Check types"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: yarn
      - name: Check types
        run: yarn check-types

  build:
    runs-on: ubuntu-latest
    needs: [eslint, check-types]
    name: "Build node app"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: yarn
      - name: Build lib
        run: yarn build
      
    
